name: surge

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    name: Deploying to surge
    
    steps:
    - uses: actions/checkout@v1
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install --global surge
      run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
        
